- sequence_member/src/main/java/sequence/sequence_member/archive/controller/ArchiveController.java
- sequence_member/src/main/java/sequence/sequence_member/archive/controller/TeamEvaluationController.java
- sequence_member/src/main/java/sequence/sequence_member/archive/dto/ArchiveMemberDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/dto/ArchiveRegisterInputDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveService.java
1. SecurityConfig에서 권한설정을 해주거나 @Seucred 어노테이션등을 통해 로그한 유저만 접근할 수 있도록 하는 방법이 있는데, 혹시 따로 userDetails가 null인걸 검사하는 이유가 있을까요
---
Secured 어노테이션을 활용하도록 수정했습니다.
2. 동작은 크게 다르지 않다면 하나의 메서드로도 동작할 수 있게 하는건 어떨까요? 그 안에서 null검사를 통해 로직을 진행하는게 더 좋을 것 같아서요! 이렇게 하면 중복되는 코드가 많아 질 것 같습니다 :)
---
하나의 메서드로 동작할 수 있도록 했습니다.
3. if else if else 구조는, 나중에 조건을 추가하거나,
디버깅을 할때 어떤 조건문에서 오류가 발생하였는지 파악하기 어려워서
유지보수가 힘들기 때문에
저는 간단한 조건문이라도 가독성과 유지보수를 위해 지양하는 편입니다.
---
당장은 간단한 코드라서 if, else if를 유지하도록 했습니다.
4. ApiResponseData를 응답하도록 되어있는데 *(와일드카드)를 쓰신 이유가 있을까요?
---
적절하지 않은 와일드 카드 사용이라 수정했습니다.
5. 해당 메서드에 특별히 produces 속성을 설정한 이유가 있을까요?
---
불필요한 속성이므로 수정했습니다.
6. 내부 클래스로 구현하신 이유가 있을까요?
---
잘못 작성된 코드입니다. 수정했습니다.
> 코드 리뷰 의견 반영

- sequence_member/src/main/java/sequence/sequence_member/global/exception/GlobalExceptionHandler.java
- sequence_member/src/main/java/sequence/sequence_member/global/minio/service/MinioService.java
- sequence_member/src/main/java/sequence/sequence_member/global/utils/FileExtension.java
- sequence_member/src/main/java/sequence/sequence_member/global/utils/FileExtensionImpl.java
- sequence_member/src/main/java/sequence/sequence_member/global/utils/MultipartUtil.java
- sequence_member/src/main/java/sequence/sequence_member/member/entity/MemberEntity.java
- sequence_member/src/main/java/sequence/sequence_member/member/service/MemberService.java
- sequence_member/src/main/resources/application.yml
목적 :
- 미니오 서버에 프로필 이미지를 저장
- 저장된 프로필 이미지 url을 DB에 저장
- MinioService, MultipartUtil의 순환참조 문제 해결하여 이미지를 서버에 업로드 가능하도록 하기
- 인터페이스를 제작하고 구현체를 만들어서 DIP를 준수한 구조 설계
목표:
- MinioService에서 사용하는 MultipartUtil함수들을 인터페이스로 만들고, 구현체를 작성
- 해당 인터페이스를 MinioService가 참조하도록 하여서 DIP 준수 및 순환참조 문제 해결
- 프로필 이미지를 서버에 업로드 하고 해당 url을 데이터베이스에 저장
기타 :
- 프로젝트 이미지 여러장 업로드 기능 구현 필요
- 아카이브 썸네일 이미지 업로드 기능 구현 필요
> refactor : 프로필 이미지 업로드 시 발생하는 순환참조 문제 해결, 이미지 url 데이터베이스에 저장

- sequence_member/src/main/java/sequence/sequence_member/archive/controller/ArchiveBookmarkController.java
- sequence_member/src/main/java/sequence/sequence_member/archive/controller/ArchiveCommentController.java
- sequence_member/src/main/java/sequence/sequence_member/archive/dto/ArchiveCommentOutputDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/dto/ArchiveOutputDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/dto/CommentCreateRequestDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/dto/CommentPageResponseDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/dto/CommentResponseDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/dto/CommentUpdateRequestDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/entity/Archive.java
- sequence_member/src/main/java/sequence/sequence_member/archive/entity/ArchiveBookmark.java
- sequence_member/src/main/java/sequence/sequence_member/archive/entity/ArchiveComment.java
- sequence_member/src/main/java/sequence/sequence_member/archive/repository/ArchiveBookmarkRepository.java
- sequence_member/src/main/java/sequence/sequence_member/archive/repository/ArchiveCommentRepository.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveBookmarkService.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveCommentService.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveService.java
- sequence_member/src/main/java/sequence/sequence_member/member/dto/CustomUserDetails.java
- 북마크 테이블 따로 분리, 누가 무엇을 북마크 했는지 알 수 있도록 수정
- 아카이브 조회 시 로그인 한 유저가 이 아카이브를 북마크 했는지 true, false로 표시
- 아카이브 조회 시 댓글 리스트 추가
> 북마크, 댓글 기능 추가

- sequence_member/src/main/java/sequence/sequence_member/member/config/SecurityConfig.java
- sequence_member/src/main/java/sequence/sequence_member/member/controller/DeleteMemberController.java
- sequence_member/src/main/java/sequence/sequence_member/member/service/DeleteService.java
- 기존의 유저 탈퇴 처리 방법을 변경 (Member의 isDeleted로 유저 구분)
- 탈퇴 유저 확인 API 추가
> feat : 유저 탈퇴 로직 변경

- sequence_member/src/main/java/sequence/sequence_member/archive/repository/ArchiveRepository.java
- sequence_member/src/main/java/sequence/sequence_member/member/converter/DesiredJobConverter.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/controller/MyPageController.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/MyPageMapper.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/MyPageRequestDTO.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/MyPageResponseDTO.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/service/MyPageService.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/service/MyPageUpdateService.java
[목적]: 사용자 정보를 조회할 때 아카이브에 대한 정보 리턴
[목표]: 아카이브에 대한 정보를 리턴할 때 페이지네이션을 이용하도록
[달성도]:
- 아카이브에 대한 정보를 리턴하도록 로직 수정
- DesiredJobConverter의 클래스 이름 오류 해결
> [feat]: 마이페이지 리턴시 아카이브 정보 추가

- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveService.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/MyPageMapper.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/MyPageResponseDTO.java
[목적]: 아카이브 멤버 엔티티 변경으로 인한 에러를 해결하기 위해서.
[목표]: 마이페이지에서 DTO 매핑 부분 수정하여 에러 해결.
[달성도]:
- 아카이브 멤버 엔티티 변경으로 인한 에러 해결.
- 마이페이지에서 DTO 매핑 부분 수정 완료.
[기타]: 아카이브 리스트 오류 해결 필요.
> [fix]: 마이페이지 아카이브 DTO 매핑 수정

- sequence_member/src/main/java/sequence/sequence_member/member/config/SecurityConfig.java
- sequence_member/src/main/java/sequence/sequence_member/report/controller/ReportController.java
- sequence_member/src/main/java/sequence/sequence_member/report/dto/ReportRequestDTO.java
- sequence_member/src/main/java/sequence/sequence_member/report/dto/ReportResponseDTO.java
- sequence_member/src/main/java/sequence/sequence_member/report/entity/ReportEntity.java
- sequence_member/src/main/java/sequence/sequence_member/report/service/ReportService.java
- 기존 String 타입의 ReportType을 enum으로 변경.
- 동일한 사용자가 동일한 대상에 대해 중복 신고하는 것을 방지하는 로직 추가.
> feat : 신고 중복 방지 및 ReportType 입력 방식 변경

- sequence_member/src/main/java/sequence/sequence_member/global/minio/service/MinioService.java
- sequence_member/src/main/java/sequence/sequence_member/global/utils/FileExtensionImpl.java
- sequence_member/src/main/java/sequence/sequence_member/global/utils/MultipartUtil.java
- sequence_member/src/main/java/sequence/sequence_member/member/controller/MemberController.java
- sequence_member/src/main/java/sequence/sequence_member/member/dto/MemberDTO.java
- sequence_member/src/main/java/sequence/sequence_member/member/entity/MemberEntity.java
- sequence_member/src/main/java/sequence/sequence_member/member/entity/PortfolioEntity.java
- sequence_member/src/main/java/sequence/sequence_member/member/repository/PortfolioRepository.java
- sequence_member/src/main/java/sequence/sequence_member/member/service/MemberService.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/service/MyPageService.java
- sequence_member/src/main/resources/application.yml
목적 :
- 포트폴리오 첨부 기능 추가
- 포트폴리오 여러개 첨부 가능
목표 :
- 미니오 서버에 여러개 포트폴리오 업로드 가능하도록 함
- 포트폴리오는 pdf만 업로드 가능하도록 함
달성도 :
- 구현 완료
> feat : 포트폴리오 첨부 기능

- sequence_member/src/main/java/sequence/sequence_member/archive/dto/ArchiveMemberDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/dto/ArchiveOutputDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/entity/Archive.java
- sequence_member/src/main/java/sequence/sequence_member/archive/entity/ArchiveMember.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveService.java
- sequence_member/src/main/java/sequence/sequence_member/archive/utill/RedisKeyManager.java
> role 삭제 및 조회수 정상화

- sequence_member/src/main/java/sequence/sequence_member/archive/dto/ArchiveRegisterInputDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveService.java
archive register input dto에 img url이 누락되어 추가 및 service도 그에 맞게 수정 후 핫픽스
> img url dto 수정

- sequence_member/src/main/java/sequence/sequence_member/member/config/SecurityConfig.java
- sequence_member/src/main/java/sequence/sequence_member/report/controller/ReportController.java
- sequence_member/src/main/java/sequence/sequence_member/report/dto/ReportTargetDTO.java
- sequence_member/src/main/java/sequence/sequence_member/report/service/ReportService.java
[목적]: 신고하기 페이지에서 보이게 될 피신고자의 정보를 전달하기 위함
[목표]: 신고자의 정보를 불러 올 수 있는 API 추가
> feat: 신고 전 사용자 정보 조회 기능 추가

- sequence_member/src/main/java/sequence/sequence_member/archive/controller/ArchiveController.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveService.java
> 리스트 비어있을 때 500 에러 처리하지 않도록 수정

- sequence_member/src/main/java/sequence/sequence_member/archive/dto/ArchiveUpdateDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/entity/Archive.java
- sequence_member/src/main/java/sequence/sequence_member/archive/repository/ArchiveMemberRepository.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveService.java
> 아카이브 업데이트 수정

- sequence_member/src/main/java/sequence/sequence_member/archive/dto/ArchiveMemberDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/dto/ArchiveOutputDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/entity/Archive.java
- sequence_member/src/main/java/sequence/sequence_member/archive/repository/ArchiveBookmarkRepository.java
- sequence_member/src/main/java/sequence/sequence_member/archive/repository/ArchiveRepository.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveService.java
- sequence_member/src/main/java/sequence/sequence_member/global/exception/AuthException.java
- sequence_member/src/main/java/sequence/sequence_member/global/utils/DataCreateService.java
- sequence_member/src/main/java/sequence/sequence_member/member/controller/MemberController.java
- sequence_member/src/main/java/sequence/sequence_member/member/entity/PortfolioEntity.java
- sequence_member/src/main/java/sequence/sequence_member/member/service/MemberSearchService.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/controller/MyPageController.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/MyActivityResponseDTO.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/MyArchiveDTO.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/MyProjectDTO.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/PostDTO.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/service/MyPageService.java
- sequence_member/src/main/java/sequence/sequence_member/project/controller/ProjectController.java
- sequence_member/src/main/java/sequence/sequence_member/project/repository/ProjectBookmarkRepository.java
- sequence_member/src/main/java/sequence/sequence_member/project/repository/ProjectRepository.java
- sequence_member/src/main/java/sequence/sequence_member/project/service/ProjectBookmarkService.java
- 자동으로 작성자는 멤버에 추가
- 본인은 닉네임 검색결과에서 제외하도록 수정
- 아카이빙 엔티티에 작성자 정보 추가
- 아카이빙 리스트/단일 조회시 작성자 닉네임도 함께 전달
> hotfix : archive 수정

- sequence_member/src/main/java/sequence/sequence_member/archive/controller/ArchiveBookmarkController.java
- sequence_member/src/main/java/sequence/sequence_member/archive/entity/ArchiveBookmark.java
- sequence_member/src/main/java/sequence/sequence_member/archive/repository/ArchiveBookmarkRepository.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveBookmarkService.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveService.java
- sequence_member/src/main/java/sequence/sequence_member/member/entity/MemberEntity.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/service/MyPageService.java
> bookmark username -> userId

- sequence_member/src/main/java/sequence/sequence_member/archive/controller/TeamEvaluationController.java
- sequence_member/src/main/java/sequence/sequence_member/archive/dto/TeamEvaluationResponseDto.java
- sequence_member/src/main/java/sequence/sequence_member/archive/entity/Archive.java
- sequence_member/src/main/java/sequence/sequence_member/archive/entity/TeamEvaluation.java
- sequence_member/src/main/java/sequence/sequence_member/archive/repository/ArchiveRepository.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveService.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/TeamEvaluationService.java
1. 팀원평가 조회 시 응답에 startDate, endDate 추가
2. 모든 팀원이 평가 완료 시 status 자동 update
3. 아카이브 리스트 조회 시 status가 평가완료인 아카이브만 조회
> 팀원평가 날짜추가, archive status 기능 추가

- sequence_member/src/main/java/sequence/sequence_member/alarm/controller/alarmController.java
- sequence_member/src/main/java/sequence/sequence_member/archive/repository/ArchiveRepository.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveService.java
- 아카이빙을 가져올때 평가가 완료된것만 가져오도록 메서드가 수정되어있어 별도의 알람을 위한 메서드를 추가함.
> hotfix : 알람에서 아키이빙 가져오는 것 수정

- sequence_member/src/main/java/sequence/sequence_member/member/dto/AcceptProjectOutputDTO.java
- sequence_member/src/main/java/sequence/sequence_member/member/service/InviteAccessService.java
> fix : 본인이 참여하는 프로젝트 리스트 조회 수정

- sequence_member/src/main/java/sequence/sequence_member/archive/dto/ArchiveListDTO.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveService.java
리스트 조회 시 북마크갯수, 조회수, 댓글 수 반환 추가
"archives": [
{
"id": 45,
"title": "프로젝트 제목2",
"writerNickname": "닉sadf테4",
"thumbnail": "url",
"commentCount": 2,
"view": 1,
"bookmarkCount": 1,
"createdDateTime": "2025-03-30T02:48:59.2767"
},
> 리스트 조회 시 북마크갯수, 조회수, 댓글 수 반환 추가

- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/MyActivitiesDTO.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/MyPageMapper.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/service/MyPageService.java
[목적]
- portfolioDTO 초대된 프로젝트 정보 아니었는데 초대된 프로젝트로 변경
- MyActivitiesDTO에 createdDate를 yyyy-mm-dd로 포맷팅
[변경 내용]
- ArchiveSummaryDTO 초대된 프로젝트 정보
- MyActivitiesDTO에 createdDate를 String으로 변경하고 포맷팅
[결과]
- MyPage 관련 DTO 구조 및 반환 데이터의 업데이트
- 코드 가독성 및 유지보수성 개선
> [refactor]: MyPageResponseDTO의 PortfolioDTO 변경

- sequence_member/src/main/java/sequence/sequence_member/archive/entity/TeamEvaluation.java
- sequence_member/src/main/java/sequence/sequence_member/archive/repository/TeamEvaluationRepository.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/MyPageEvaluationService.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/TeamEvaluationService.java
keyword 파싱 수정
평가를 repository에서 findByEvaluatedId가 없어서 id를 못찾고 있었어서 수정
> 마이페이지 조회 시 팀원평가 데이터 fix

- sequence_member/src/main/java/sequence/sequence_member/project/controller/ProjectController.java
- sequence_member/src/main/java/sequence/sequence_member/project/dto/ProjectFilterOutputDTO.java
- sequence_member/src/main/java/sequence/sequence_member/project/repository/ProjectRepository.java
- sequence_member/src/main/java/sequence/sequence_member/project/service/ProjectService.java
- 프로젝트 필터링 기능에 페이지네이션 추가
- api 명세서 최신화 추가
> feat : 프로젝트 페이지네이션 추가

- sequence_member/src/main/java/sequence/sequence_member/global/config/JpaAuditingConfig.java
- sequence_member/src/main/java/sequence/sequence_member/global/config/UserAuditorAware.java
- sequence_member/src/main/java/sequence/sequence_member/global/utils/BaseTimeEntity.java
- by, deletedBy, deletedAt 추가
- AuditorAware로  by 자동 추가
- soft-delete 방식 추가
> fix : baseEntity 수정

- .github/workflows/test-server-prTest
- .github/workflows/test-server-release
- sequence_member/src/main/java/sequence/sequence_member/member/controller/TokenReissueController.java
- sequence_member/src/main/java/sequence/sequence_member/member/jwt/LoginFilter.java
- sequence_member/src/main/java/sequence/sequence_member/project/entity/Project.java
- sequence_member/src/main/java/sequence/sequence_member/project/repository/ProjectBookmarkRepository.java
- sequence_member/src/main/java/sequence/sequence_member/project/service/ProjectBookmarkService.java
- sequence_member/src/main/java/sequence/sequence_member/project/service/ProjectService.java
access 토큰 : 1시간
refresh 토큰 : 7일
> refactor : 토큰 유효시간 서비스 운영에 맞게 변경

- sequence_member/src/main/java/sequence/sequence_member/mypage/controller/MyPageController.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/BasicInfoDTO.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/MyPageMapper.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/service/MyPageService.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/service/MyPageUpdateService.java
[목적]
- 사용자가 마이페이지에서 프로필 이미지를 등록 및 변경할 수 있도록 기능 제공
[변경 내용]
- MultipartFile을 통해 전달된 프로필 이미지 파일 처리 로직 추가
- 파일명 생성 유틸리티(MultipartUtil) 활용하여 MinIO 저장소에 파일 업로드
- MemberEntity의 profileImg 필드 업데이트 처리
[결과]
- 사용자가 마이페이지 수정 시 프로필 이미지를 등록하거나 수정할 수 있음
> [feat]: 마이페이지 프로필 이미지 업데이트 기능 추가

- sequence_member/src/main/java/sequence/sequence_member/global/enums/enums/Skill.java
- sequence_member/src/main/java/sequence/sequence_member/member/config/SecurityConfig.java
- sequence_member/src/main/java/sequence/sequence_member/member/controller/MemberController.java
- sequence_member/src/main/java/sequence/sequence_member/member/converter/SkillCategoryConverter.java
- sequence_member/src/main/java/sequence/sequence_member/member/dto/MemberDTO.java
- sequence_member/src/main/java/sequence/sequence_member/member/entity/EducationEntity.java
- sequence_member/src/main/java/sequence/sequence_member/member/service/MemberService.java
목적 :
- skill enum값들 추가
- skill enum <-> skill string 컨버터 추가
> feat : skill enum 추가 및 컨버터 추가

- sequence_member/src/main/java/sequence/sequence_member/member/controller/SkillController.java
- sequence_member/src/main/java/sequence/sequence_member/member/service/SkillService.java
- 전체 스킬 카테고리를 map으로 반환 -> List<String>으로 반환
> refactor : 전체 스킬 카테고리 반환 api 수정

- sequence_member/src/main/java/sequence/sequence_member/member/controller/MemberController.java
- sequence_member/src/main/java/sequence/sequence_member/member/repository/MemberRepository.java
- sequence_member/src/main/java/sequence/sequence_member/member/service/MemberSearchService.java
- 탈퇴한 멤버도 프로젝트 생성에서 조회되는 것을 수정
- 탈퇴한 멤버의 닉네임은 조회되지 않음
> fix : 탈퇴한 멤버도 조회되는 오류 수정

- sequence_member/src/main/java/sequence/sequence_member/archive/entity/ArchiveComment.java
- sequence_member/src/main/java/sequence/sequence_member/archive/repository/ArchiveCommentRepository.java
- sequence_member/src/main/java/sequence/sequence_member/archive/repository/ArchiveRepository.java
- sequence_member/src/main/java/sequence/sequence_member/archive/repository/TeamEvaluationRepository.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveCommentService.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/ArchiveService.java
- sequence_member/src/main/java/sequence/sequence_member/archive/service/TeamEvaluationService.java
- sequence_member/src/main/java/sequence/sequence_member/mypage/dto/MyPageMapper.java
BaseTimeEntity의 softDelete 사용해 적용 완료.
> 아카이브, 팀원평가, 아카이브 댓글 softdelete 적용 완료.

- sequence_member/src/main/java/sequence/sequence_member/project/entity/Project.java
https://agongstory.tistory.com/86
> fix : 프로젝트 북마크 등록 오류 해결
